config/routes.rb
Rails.application.routes.draw do
  
  root 'games#index'
  post 'change' => 'games#change'
  post 'join' => 'games#join'
  resources :games
  resources :users
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#logout'

end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :user
  
  after_initialize :convert_from_string
  before_save :convert_to_string

  def convert_from_string
    if (self.grid.nil?)
      grid = Grid.new
      @initial_grid = grid
      self.game_status = 0
    else
      @initial_grid = Grid.from_s(self.grid)
    end
  end

  def convert_to_string
    self.grid = @initial_grid.to_s
  end

  def initial_grid
    @initial_grid
  end

  def check_status
    return initial_grid.check_game_status(self.player_number)
  end

end

app/models/grid.rb
class Grid
  def initialize(array = ['_', '_', '_', '_', '_', '_', '_', '_', '_'])
    @numbers = array
  end

  def to_s
    return @numbers.join(",")
  end

  def self.from_s(string)
    array = string.split(",")
    return Grid.new(array)
  end

  def numbers
    @numbers
  end

  def check_game_status(current_player)
    @player = current_player == true ? 'X' : 'O'

    # check rows
    $k = 0
    while $k < 8
      for i in 0..2
        if (@numbers[$k + i] == @player)
          if (i == 2)
            return 1
          end
        else
          break
        end
      end
      $k += 3
    end

    # check columns
    $k = 0
    for i in 0..2
      while $k < 8
        if (@numbers[$k + i] == @player)
          if ($k > 5)
            return 1
          end
          $k += 3
        else
          $k = 0
          break
        end
      end
    end

    # check diagonals
    if (@numbers[2] == @player && @numbers[4] == @player && numbers[6] == @player)
      return 1
    elsif (@numbers[0] == @player && @numbers[4] == @player && numbers[8] == @player)
      return 1
    end

    # check if game is draw (all spaces have been used)
    for i in 0..8
      if (@numbers[i] == "_")
        break
      elsif i == 8
        return 2
      end
    end

    # game continues if none of the above conditions have been met
    return 0
          

  end

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save :downcase_email
  validates :email, presence: true
  has_many :games
  has_secure_password

  private
    def downcase_email
      self.email = email.downcase
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper


  private
    def require_login
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  
  before_action :require_login, :only => [:create, :join, :edit, :change]
  
  def index
    @games = Game.where("opponent IS NULL ")
  end

  def create
    @game = current_user.games.build

    if @game.save
      redirect_to edit_game_path(@game)
    else
      redirect_to :back
    end
  end

  def join
    @games = Game.all
    @game = Game.find(params[:id])

    if check_opponent(@games, @game) == 0 && @game.update_attribute(:opponent, current_user.id)
      redirect_to edit_game_path(@game)
    else
      flash[:danger] = "Already in game with this player"
      redirect_to root_path
    end
  end

  def edit
    @game = Game.find(params[:id])
  end

  def show
    @game = Game.find(params[:id])
  end

  def change
    @game = Game.find(params[:id])

    #finds current player and changes the chosen position to an X or O
    @player = @game.player_number == true ? 'X' : 'O'
    @game.initial_grid.numbers[params[:number].to_i] = @player
    
    @status = @game.check_status

    if @game.save
      # checks if game is finished (win or draw), otherwise changes player and goes back to game
      if @status == 1 || @status == 2
        @game.update_column(:game_status, @status)
        redirect_to game_path(params[:id])
      else
        @game.player_number == true ? @game.update_column(:player_number, false) : @game.update_column(:player_number, true)
        redirect_to edit_game_path(params[:id])
      end
    else
      redirect_to root_path
    end
  end

  private

    def check_opponent(games, requested_game)
      @list_current_opponents = []
      # finds all current opponents, those who have joined your games or vice versa
      games.each do |game|
        if game.user_id == current_user.id && game.game_status == 0
          @list_current_opponents.push(game.opponent)
        end
        if game.opponent == current_user.id && game.game_status == 0
          @list_current_opponents.push(game.user_id)
        end
      end
      @new_opponent = 0
      # checks current opponents are not in the game you are about to join
      @list_current_opponents.each do |id|
        if id == requested_game.user_id
          @new_opponent = 1
        end
      end
      return @new_opponent
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      login(user)
      redirect_to root_path
    else
      render 'new'
    end
  end

  def logout
    log_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def new
    @user = User.new
  end

  def create
    @user = User.new(permitted_params)
    if @user.save
      redirect_to login_path
    else
      render 'new'
    end
  end

  private
    def permitted_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def login(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    current_user
  end

  def log_out
    @current_user = nil
    session.delete(:user_id)
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/edit.html.haml
- if @game.game_status == 0
  - if ((@game.player_number == true && current_user.id == @game.user_id) || @game.player_number == false && current_user.id == @game.opponent)
    %table
      - (0..2).each do |i|
        %tr
          - (0..2).each do |j|
            %td
              - if @game.initial_grid.numbers[3 * i + j] == "_"
                = link_to change_path(:number => 3 * i + j, :id => @game.id), method: :post do
                  = @game.initial_grid.numbers[3 * i + j]
              - else
                = @game.initial_grid.numbers[3 * i + j]
  - else
    %p= "Please wait for your turn and then refresh the page"
- else
  %p= "Game already finished, gameplay is no longer allowed"
  = link_to "Result", game_path(@game)

app/views/games/index.html.haml
#home

  %p= "To start or join a game, please login."
  
  #new_game
    = link_to "New Game", games_path, method: :post

  #games
    %p= "List of Games"
    - @games.each do |game|
      #game
        - if logged_in?
          - if game.user_id != current_user.id && game.game_status == 0
            = game.id
            = link_to "Join Game", join_path(:id => game.id), method: :post
        - else
          = game.id
          = link_to "View Game", game_path(game)

app/views/games/show.html.haml
- if @game.game_status == 0
  %p= "Game is still in action"
- elsif @game.game_status == 1
  %p= "Player #{@game.player_number ? "X" : "O"} won the game"
- else
  %p= "Game was a draw"

%table
  - (0..2).each do |i|
    %tr
      - (0..2).each do |j|
        %td
          = @game.initial_grid.numbers[3 * i + j]

app/views/layouts/_header.html.haml
#header
  = link_to "Home", root_path
  - if logged_in?
    = link_to "Profile", current_user
    = link_to 'Logout', logout_path,  method: :delete
  - else
    = link_to "Login", login_path
    = link_to "Signup", new_user_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Tictactoe
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    - flash.each do |message_type, message|
      = message
    = yield
    = debug(params) if Rails.env.development?

app/views/users/new.html.haml
%h2= "Signup"

= form_for @user do |f|
  = f.label :email   
  = f.email_field :email, required: true
  = f.label :password    
  = f.password_field :password, required: true
  = f.label :password_confirmation    
  = f.password_field :password_confirmation, required: true   
  = f.submit "Submit"